---
- name: set hostnames
  ansible.builtin.shell: hostnamectl set-hostname {{ var_hostname }}

- name: enable cgroup and swap
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'

- name: Remove snaps
  community.general.snap:
    name:
      - lxd
      - core20
      - snapd
    state: absent
  ignore_errors: yes

- name: remove snapd
  ansible.builtin.apt:
    name: snapd
    state: absent
    purge: yes
    autoremove: yes

- name: install linux modules
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
    state: present

- name: install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present

- name: Installing cifs and nfs packages
  ansible.builtin.apt:
    pkg:
      - cifs-utils
      - jq
      - util-linux
      - coreutils
      - nfs-common
    state: latest
  register: installation
  become: true

- name: create directory for cifs
  ansible.builtin.file:
    path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/fstab~cifs
    state: directory
    mode: '0755'

- name: Cloning cifs flexvolume
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/fstab/cifs/master/cifs
    dest: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/fstab~cifs
    mode: '0755'

- name: update packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
