---
# openssh secure
- name: Check if openssh is running
  ansible.builtin.command: 
    cmd: systemctl status ssh
  ignore_errors: yes
  changed_when: false
  register: service_ssh_status

- name: openssh - Disallow password authentication
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  when: service_ssh_status is not failed

- name: openssh - Disallow root SSH access
  ansible.builtin.lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: restart ssh
  when: service_ssh_status is not failed
