---
# set hostname
- name: Setting Hostname
  ansible.builtin.shell: "hostnamectl set-hostname {{ inventory_hostname }}"

# cmdline edit

- name: Changing CMDLINE for containers
  ansible.builtin.shell: "sed -i '$ s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1/' /boot/cmdline.txt"